### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by TheFrenchGhosty** [cloudrac3r/bibliogram#27]
I like the theme Bibliogram uses... but at night my eyes don't sadly.

The biggest issue is the #EEEEEE on the posts/profiles pages but the other colors could be darker too (a dark-red for the homepage maybe?).

**Comment by cloudrac3r** [comment]
Waiting on #28

**Comment by mendel5** [comment]
I've created a dark theme for Bibliogram. The account that was used is https://bibliogram.art/u/troyhunt .

Bibliogram light theme (current version):
![bibliogram_light-theme](https://user-images.githubusercontent.com/60322520/79636025-23ccc300-8175-11ea-8127-e84f6a629eb8.png)

Bibliogram dark theme (new version):
![bibliogram-dark-theme](https://user-images.githubusercontent.com/60322520/79636036-2fb88500-8175-11ea-8bda-321793746ab7.png)

Colors used:
* [#807D7A](https://convertingcolors.com/hex-color-807D7A.html) for background. This color is a complimentary color to the current background color [#FFF4E8](https://convertingcolors.com/hex-color-FFF4E8.html).
* [#FFFFFF](https://convertingcolors.com/hex-color-FFFFFF.html) for text color. It's the opposite of the current text color [#000000](https://convertingcolors.com/hex-color-000000.html)
* [#000000](https://convertingcolors.com/hex-color-000000.html) for profile overview. It's the opposite of the current color [#FFFFFF](https://convertingcolors.com/hex-color-FFFFFF.html)
* [#FFB8B8](https://convertingcolors.com/hex-color-FFB8B8.html) for link color. This is the same link color as on the start page of Bibliogram (e.g. "See an example" on https://bibliogram.art/ ).
* [#000000](https://convertingcolors.com/hex-color-000000.html) and [#FFFFFF](https://convertingcolors.com/hex-color-FFFFFF.html) for the page number and separator in the timeline.
* [#FFFFFF](https://convertingcolors.com/hex-color-FFFFFF.html) and padding of 3px on the profile picture (.pfp).

**Comment by cloudrac3r** [comment]
Thanks for this. I like the ring around the profile picture. I expect I'll adjust these colours a little when i actually make the dark theme. It's still waiting on the settings page, which I should really hurry up and do to unlock about half of the open issues.

**Comment by cloudrac3r** [comment]
I think I'll use #ee4646 for the link colour, since the one you've suggested [probably doesn't contrast with the text colour well enough.](https://axesslab.com/colorblind-accessibility-web-fail-success-cases/)

**Comment by mendel5** [comment]
I like your link color better. It's more vibrant than the color I proposed before. Here is a comparison:
* [#FFB8B8](https://convertingcolors.com/hex-color-FFB8B8.html) - [#EE4646](https://convertingcolors.com/hex-color-EE4646.html)

Yes, I think a lot of people would appreciate the settings page.

**Comment by mendel5** [comment]
Here is the new version of the dark theme. I now used [#EE4646](https://convertingcolors.com/hex-color-EE4646.html) for the link color and removed the black box in the timeline page separator.
![bibliogram_dark-theme_2](https://user-images.githubusercontent.com/60322520/79643928-d288f780-81a5-11ea-849b-2c2b4c1cf9b0.png)

**Comment by cloudrac3r** [comment]
The settings page exists and there is a template for this setting, so it's no longer waiting, but I should restructure the Sass to allow easy theming first. Then you can go nuts and change all the colours you want. I'm perfectly fine with adding many themes like Nitter has, so once that's done, feel free to submit your favourite colours in a pull request.

After that. feel free to work on creating the first official dark theme in Bibliogram, but note that whatever you end up with will be subject to my own personal opinions and modifications, because it's the _first_ dark theme. I will probably not be picky about subsequent themes, provided that the contrast between text and background complies with WCAG AA (contrast ratio must be at least 4.5:1), so feel free to design completely opinionated styles _after_ the first official dark theme and they'll likely be accepted.

Hope that made sense.

**Comment by mendel5** [comment]
I have created a pull request (see https://github.com/cloudrac3r/bibliogram/pull/61 ) for the dark theme. What do you think of it? I am open for feedback.

**Comment by cloudrac3r** [comment]
I've created a wiki page explaining how to create themes, if any lurkers on this issue want to try creating their own theme. Let me know if something's wrong. https://github.com/cloudrac3r/bibliogram/wiki/Creating-themes

**Comment by mendel5** [comment]
Thank you, I will have a look!

**Comment by B0pol** [comment]
It's done

**Comment by TheFrenchGhosty** [comment]
The pussthecat.org dark theme isn't *the* Bibliogram dark theme, nor was it ever supposed to be. Bibliogram needs it's specific dark theme.

**Comment by cloudrac3r** [comment]
@mendel5 appears to be absent from this, so I'll create a theme based on their colour values if I don't hear anything from them soon.

**Comment by mendel5** [comment]
@cloudrac3r As far as I can tell it is currently not possible to change the color of this "Loading..." notice from within the themes.
![loading](https://user-images.githubusercontent.com/60322520/83359570-53c5d380-a37b-11ea-9fb6-f6f13bd03cc4.png)
Or I just overlooked something...

**Comment by mendel5** [comment]
The color of the disabled buttons on the settings page is "[#dfd6cb](https://www.color-hex.com/color/dfd6cb)". However this color is also not included in the "classic.scss" file. Am I looking in the wrong place?

**Comment by mendel5** [comment]
The progress on my theme is quite good so far. However one thing I was not able to include from within my theme is the white border around the profile picture (see screenshots above). Can you tell me how to do it?

**Comment by cloudrac3r** [comment]
It is currently not possible to change the loading notice.

It is currently not easy to change the controls on the settings page, and I will definitely make values for this at some point.

In the .sass file, add this code at the bottom:

    .pfp
        border: 2px solid #fff

That should get you started.

**Comment by cloudrac3r** [comment]
I've created my own dark theme based on Discord's appearance. I decided to put it above PussTheCat.org, since as @TheFrenchGhosty keeps insisting, their theme is not supposed to be the main dark theme.

Here's [a link to the commit as a reference](https://github.com/cloudrac3r/bibliogram/commit/7bd43ca857a60a177e0dc3168744fc2c9670fa88?diff=unified) to help anyone in this thread create their own theme. You can see that the process is now a lot more streamlined than what it used to be! :D 

(note: I do not like Discord, it just has decent colours)

**Comment by cloudrac3r** [comment]
This has been inactive for 2 weeks, and there are several dark themes now, so I'll close this issue. @mendel5, if you wish to continue working on your theme, I'd still love to see how it turns out!
