### ISSUE TITLE
Display the date on a post

### ISSUE THREAD

**Issue by TheFrenchGhosty** [cloudrac3r/bibliogram#3]
Right now there is no way to know when a post was made, it would be nice if the date was displayed on its page.

**Comment by mendel5** [comment]
Hi Cadence, I started working on this issue. I have found two methods to get the date.

Method 1:
* Example image on Instagram.com: https://www.instagram.com/p/BsSSJyAA-7c/
* Same image on Bibliogram.art: https://bibliogram.art/p/BsSSJyAA-7c/
* As far as I can tell, what happens next is that bibliogram requests this page: https://bibliogram.art/fragment/post/BsSSJyAA-7c
* The response is a JSON which includes this content: `alt=\"Photo by Troy Hunt on January 06, 2019.\"`
* So there is the date

Method 2:
* Go to https://github.com/cloudrac3r/bibliogram/blob/8398049f02ea5e4dacceb861d43ff0c39dde08b3/src/lib/collectors.js#L322
* replace example with shortcode from above: `BsSSJyAA-7c`
* https://www.instagram.com/graphql/query/?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables={%22shortcode%22:%22BsSSJyAA-7c%22,%22child_comment_count%22:3,%22fetch_comment_count%22:40,%22parent_comment_count%22:24,%22has_threaded_comments%22:true}
* The JSON response contains this: `"taken_at_timestamp":1546761752,`
* According to https://www.unixtimeconverter.io/1546761752 this unix timestamp translates to `Sun, 06 Jan 2019 08:02:32 +0000` .
* This method is more precise

I think that method 1 internally calls method 2 but I couldn't figure out where the unix timestamp from method 2 gets converted to the image alt tag from method 1. Do you know where that happens?

**Comment by cloudrac3r** [comment]
The TimelineEntry class should always have taken_at_timestamp available in its data. Please use that instead of trying to parse accessibility_caption.

accessibility_caption is provided by Instagram directly, I do not do any additional processing on it. Sometimes the caption is provided, sometimes it is not. Sometimes it contains the date, sometimes it does not.

You should be able to modify the pug file in src/site/pug/includes/post.pug to create a new element somewhere on the post page and set its contents to taken_at_timestamp, and then you will see the number on the page.

Once you have done that, you can try to format it into something more friendly using either JavaScript Date objects or the Intl API. You can look up how to use these on the MDN website.

**Comment by mendel5** [comment]
I've tried it locally, but somehow it doesn't work. Can you help me?

**Comment by cloudrac3r** [comment]
I can't help you without seeing the code that you tried to use and a summary of your thought process. Could you post those?

**Comment by mendel5** [comment]
Sorry for my late answer @cloudrac3r . Maybe I will pick up this issue at some point in the future, but I'm not working on it right now...

**Comment by cloudrac3r** [comment]
Did it myself in ba5a5a7653e98fa76e1490961f1815d38f5dc553.

**Comment by mendel5** [comment]
Thank you! :+1:
