### ISSUE TITLE
Input buffer contains unsupported image format

### ISSUE THREAD

**Issue by Perflyst** [cloudrac3r/bibliogram#30]
Bibliogram crashed with the following error:
```
[ ] [054357] [INC] /
[ ] [054357] [API] / = /
[ ] [054404] [INC] /u/hAcky1337
[ ] [054404] [API] /u/hAcky1337 = /u/([\w.]+)
->           [OUT] https://www.instagram.com/hAcky1337/
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: Input buffer contains unsupported image format
Emitted 'error' event on Sharp instance at:
    at /home/bibliogram/bibliogram/node_modules/sharp/lib/output.js:709:18

(sharp:15804): GLib-CRITICAL **: 05:44:16.205: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:15804): GLib-CRITICAL **: 05:44:16.205: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:15804): GLib-CRITICAL **: 05:44:16.205: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:15804): GLib-CRITICAL **: 05:44:16.205: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed

(sharp:15804): GLib-CRITICAL **: 05:44:16.205: g_hash_table_lookup: assertion 'hash_table != NULL' failed
Segmentation fault
npm ERR! code ELIFECYCLE
npm ERR! errno 139
npm ERR! bibliogram@1.0.0 start: `cd src/site && node server.js`
npm ERR! Exit status 139
```

The instance was probably blocked. The user is not in the sqlite database.

**Comment by cloudrac3r** [comment]
Cool, I got it too.

```
[ ] [005531] [INC] /u/theeconomist/rss.xml
[ ] [005531] [API] /u/theeconomist/rss.xml = /u/([\w.]+)/rss.xml
[ ] [005805] [INC] /u/hok
[ ] [005805] [API] /u/hok = /u/([\w.]+)
->           [OUT] https://www.instagram.com/hok/
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: Input buffer contains unsupported image format
Emitted 'error' event on Sharp instance at:
    at /home/cloud/bibliogram/node_modules/sharp/lib/output.js:709:18
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bibliogram@1.0.0 start: `cd src/site && node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bibliogram@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cloud/.npm/_logs/2020-02-14T00_59_59_674Z-debug.log
```

**Comment by cloudrac3r** [comment]
I don't know what to do about this except for just listening for sharp errors so they don't end the entire process (608b3a34fc804a13980a680ff63ae6f745b6b44e). If you have any bright ideas, re-open this.

**Comment by cloudrac3r** [comment]
curl -v 'https://bibliogram.art/imageproxy?url=https%3A%2F%2Fscontent-syd2-1.cdninstagram.com%2Fv%2Ft51.2885-15%2Fe35%2F37169507_236215137209475_8637817730684157952_n.jpg%3F_nc_ht%3Dscontent-syd2-1.cdninstagram.com%26_nc_cat%3D103%26_nc_ohc%3DeC-6Q8hRJGAAX_g_g-f%26oh%3D9c7b3747301d80e4d5c433ab6ca110da%26oe%3D5E89EEB9&width=150'

The images in this post ([bibliogram.art](https://bibliogram.art/p/BlZ7fFtn-jM) / [instagram](https://www.instagram.com/p/BlZ7fFtn-jM/)) are 410 GONE with response data "Gone". I do not know why. Proxying these proxies the 410 GONE, but adding `&width=`(any number) to invoke sharp emits the error, because "Gone" is not an image.

The best I could do about this is to instead return an image containing the text "this is gone", in a similar way to [how i.redd.it handles unknown images,](https://i.redd.it/1.png) but I think the current behaviour (connection closes with no data after HTTP 200) is good enough since this way the image fails to load in browsers and is replaced with its alt text.
