### ISSUE TITLE
Videos not playing in Chromium based browsers

### ISSUE THREAD

**Issue by mendel5** [cloudrac3r/bibliogram#53]
**Description**
Playing videos does not seem to work on https://bibliogram.art/ . I hope the issue is not caused on my client side.

**Examples**
* Video 1 on [Instagram.com](https://www.instagram.com/p/B-0KFHjAnhy/) and on [Bibliogram.art](https://bibliogram.art/p/B-0KFHjAnhy/) : works on Instagram but not on Bibliogram
* Video 2 on [Instagram.com](https://www.instagram.com/p/B96-0rfAQF_/) and on [Bibliogram.art](https://bibliogram.art/p/B96-0rfAQF_/) : works on Instagram but not on Bibliogram

**Comment by cloudrac3r** [comment]
Thank you for the examples, but both play for me. Please check your browser extensions — some versions of Privacy Redirect and Invidition are known to cause problems. If you enter private browsing mode, this *may* disable all extensions, so you can quickly try with no extensions enabled.

If you're still having problems, please open the developer tools, go to the network tab, reload the page with `Ctrl-F5`, and screenshot what you see once it finishes loading.

**Comment by cloudrac3r** [comment]
I've also received an email about this, and I presume it's not from you. If it is from you, please keep the discussion in here rather than continuing to email. If it's not from you, feel free to provide more information about what you're doing to solve this issue, since I don't experience it but others do.

**Comment by mendel5** [comment]
Hi Cadence, no, I didn't send you any emails.
Ok, I will try to find a solution for this. If I find something, I will let you know.

**Comment by cloudrac3r** [comment]
I can help you if you post the network logs as I previously described. You can upload images directly into GitHub comments by dragging or pasting them into the comment box.

**Comment by mendel5** [comment]
I've tested these two videos:
* https://bibliogram.art/p/B-0KFHjAnhy/
* https://bibliogram.art/p/B96-0rfAQF_/

Playing video works:
* Firefox 75.0 on Linux Mint 19.3
* Firefox 75.0 on Windows 10 1909

Playing video doesn't work:
* Chromium 80.0.3987.16 on Linux Mint 19.3
* Google Chrome 81.0.4044.113 on Windows 10 1909
* Microsoft Edge Chromium 81.0.416.58 on Windows 10 1909

**Comment by mendel5** [comment]
Maybe we can reopen this issue so others can share their findings as well?

**Comment by cloudrac3r** [comment]
Okay. I guess only happens in Chrome-based browsers, and I use Firefox.

**Comment by mendel5** [comment]
Screenshot from Firefox on Linux Mint:
![screenshot_linux-mint_firefox](https://user-images.githubusercontent.com/60322520/79633996-2a087280-8168-11ea-8e98-ba2fe52506da.png)

Screenshot from Chromium on Linux Mint:
![screenshot_linux-mint_chromium](https://user-images.githubusercontent.com/60322520/79633998-3096ea00-8168-11ea-9092-6910b4cf2453.png)

**Comment by cloudrac3r** [comment]
Do videos work now?

**Comment by mendel5** [comment]
Yes, playing video works now:
* Firefox 75.0 on Linux Mint 19.3
* Firefox 75.0 on Windows 10 1909
* Chromium 80.0.3987.16 on Linux Mint 19.3
* Google Chrome 81.0.4044.113 on Windows 10 1909
* Microsoft Edge Chromium 81.0.416.58 on Windows 10 1909

Playing video doesn't work:
* none

Thank you :)

**Comment by mendel5** [comment]
Can you @cloudrac3r tell us what caused this issue and how you fixed it? Thanks :+1:

**Comment by cloudrac3r** [comment]
See the code changes: https://github.com/cloudrac3r/bibliogram/commit/456bafa199706505e1ef02f90a029518513d61f9

[The HTTP header Range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range) requests partial content. This is important for video playback because the browser might want to request a smaller segment of the video file if the user skips ahead.

In response to the Range request header, the server must return content type 206 which indicates partial content, and also [an Accept-Ranges header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Ranges) saying if the kind of range is understood by the server.

This is enough to make Firefox work, but Chrome also requires [the Content-Range header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Range), which describes the range that the server is returning (which is hopefully the same as the range the client requested).

Bibliogram proxies video playback to protect the user from leaking their IP, avoid the browser making cross-site requests, and strip important headers that could be used for fingerprinting. For example, if all the headers were passed through, Instagram would be able to exchange cookies with the browser and easily create a session for it and track it. This is why I have a whitelist of what headers are permitted on the request and response.

Before I wasn't allowing the Content-Range response header, but Chrome requires that header to understand partial content, and partial content is required for video playback. This one was a bit of a head scratcher to figure out, but now I know. :tada:

**Comment by mendel5** [comment]
Thank you for the detailed explanation! :rocket:
