### ISSUE TITLE
User-facing endpoint for profile pages also without /u/

### ISSUE THREAD

**Issue by mendel5** [cloudrac3r/bibliogram#54]
**Description**
As described in the README.md, Bibliogram has multiple user-facing endpoints. The endpoint for a user's profile page is this one:
* `/u/{username} - load a user's profile and timeline`

However the "normal" endpoint for a user's profile on Instagram.com is instagram.com/{username} , so it's without the /u/ . Is there a reason why you @cloudrac3r decided to add the /u/? It reminds me of user profiles on Reddit.com.

**Proposal**
To make Bibliogram feel more familiar to users and make the transition easier, a user's profile should also be reachable at /{username}, just like on Instagram.com.
If this was the case, users could enable a redirect rule which redirects all requests for "instagram.com" to "bibliogram.art" (or a local instance). This is possible with e.g. the [Redirector extension](https://addons.mozilla.org/en-US/firefox/addon/redirector/) for Mozilla Firefox.

**Examples**
* Profile page on Instagram.com: https://www.instagram.com/instagram/
* Inaccessible profile page on Instagram.com: https://www.instagram.com/u/instagram/
* Profile page on Bibliogram: https://bibliogram.art/u/instagram
* Not yet accessible profile page on Bibliogram: https://bibliogram.art/instagram

**Comment by cloudrac3r** [comment]
See https://github.com/cloudrac3r/bibliogram/wiki/Reserved-URLs for some starting information.

Users being on the same level as Bibliogram information pages would be bad for a couple of reasons:
- It would make the routing code a bit harder.
- It makes it easy for users to figure out where they're going based on the URL
- It means I can create pages on Bibliogram that are for static content with URLs like /privacypolicy, /about, and /videoproxy without having to worry about these being the usernames of user accounts that would then be inaccessible. (One of these examples is actually a real user — can you guess which?)

If someone replaces instagram.com with bibliogram.art then they will get a special 404 which actually includes a link asking them if they'd like to go to the user page.

I made this decision early on for these reasons  and I do not wish to change it now.

Users can install an extension like Privacy Redirect which automatically adds the /u/ when necessary. I decided early on that I wanted extension authors to deal with this, not me.

It _is_ reminiscent of profiles on reddit! I thought /u/ rather than, say, /user/ was also fitting since Instagram already uses /p/ for posts.

**Comment by mendel5** [comment]
It is Hugo Rogov (Рогов Хуго) at https://www.instagram.com/privacypolicy/ or https://bibliogram.art/u/privacypolicy :monocle_face:

**Comment by mendel5** [comment]
Thank you for the detailed explanation. I understand that the current solution is beneficial.

The Privacy Redirect addon ([Firefox](https://addons.mozilla.org/en-US/firefox/addon/privacy-redirect/), [Chrome](https://chrome.google.com/webstore/detail/privacy-redirect/pmcmeagblkinmogikoikkdjiligflglb)) works very well!
