### ISSUE TITLE
Number of followers not shown on certain profile pages

### ISSUE THREAD

**Issue by mendel5** [cloudrac3r/bibliogram#55]
I was looking at the profile pages listed here https://en.wikipedia.org/wiki/List_of_most-followed_Instagram_accounts on both Instagram.com and Bibliogram.art.

For some reason the number of followers and number of following is not displayed on the account of "natgeo" on Bibliogram.

* https://www.instagram.com/natgeo/ numbers are shown (134m and 131)
* https://bibliogram.art/u/natgeo numbers are not shown (0 and 0)

Screenshot of natgeo on Instagram.com:
![screenshot_instagram_natgeo](https://user-images.githubusercontent.com/60322520/79634709-8b324500-816c-11ea-9f91-609e4b4cd5fd.png)

Screenshot of natgeo on Bibliogram.art:
![screenshot_bibliogram_natgeo](https://user-images.githubusercontent.com/60322520/79634712-8ec5cc00-816c-11ea-8963-4841ba3232ac.png)

**Comment by mendel5** [comment]
Number of followers also not shown:
* https://bibliogram.art/u/kendalljenner but works on https://www.instagram.com/kendalljenner/
* https://bibliogram.art/u/nickiminaj but works on https://www.instagram.com/nickiminaj/
* https://bibliogram.art/u/khloekardashian but works on https://www.instagram.com/khloekardashian/

Profile picture not shown:
* https://bibliogram.art/u/neymarjr but works on https://www.instagram.com/neymarjr/
* https://bibliogram.art/u/justinbieber but works on https://www.instagram.com/justinbieber/

**Comment by cloudrac3r** [comment]
Follower counts may be missing due to a previous method of fetching data which I've nicknamed "reel" in the code. This used to be used to look up information about a user like their profile picture URL. This method has since been superceded but old cache entries from it may still exist. I don't _think_ I can fetch new follower counts except for with a full profile page request. While I could do this, it counts towards Bibliogram's rate limit to Instagram, and the only benefit to the user would be follower counts, which are probably not very important.

I could decide to simply hide the counts instead, or use a question mark, which would probably be clearer, but currently they're stored, read, and displayed as 0.

**Comment by cloudrac3r** [comment]
Profile pictures are a completely different issue. This happens when somebody changes their profile picture because the old URL is then invalid but still cached in Bibliogram. I'm trying to make this automatically refresh, but it seems that it doesn't work properly until a cache refresh. Please open a new issue for missing profile pictures if you want it to be tracked. 2 hours later, the profiles that you linked have been through a cache cycle and now have correct pictures.

**Comment by mendel5** [comment]
I've created the issue https://github.com/cloudrac3r/bibliogram/issues/56 for the missing profile pictures.

You're right, the follower count is not that important. I would not hide the count instead but just leave it like it is.

**Comment by cloudrac3r** [comment]
69585a18ec561f2225f7cab09eefe27206678776

I replaced the counters with a "followers not available" message if they're both zero and if the "reel" method was used.

https://bibliogram.art/u/natgeo
