### ISSUE TITLE
Sort instances by Speed and Stability

### ISSUE THREAD

**Issue by allendema** [cloudrac3r/bibliogram#58]
It would be great to have a better sorting of instances, for example by Speed.
Marking instaces as unstable would be a great solution, too. 
For example right now, [https://insta.maisputain.ovh/](https://insta.maisputain.ovh/) ist not responding.

**Comment by cloudrac3r** [comment]
I believe that particular instance you pointed out is only available over IPv6. If you don't have IPv6, it might spend a long time trying and failing to connect.

Speed is problematic since it's mostly dependent on ping time to the server, which depends on country. Additionally, this my vary by load, time of day, and of course unforseen circumstances.

While I appreciate that it would be _good_ to have some measure of speed, I have no idea how it could be implemented.

Also important when choosing an instance is whether it is blocked or not. Like speed, this varies greatly over time, and it's important to show data from _right now,_ not a day ago, not a month ago.

I'm open to suggestions on how a speed index and blocked status could be accomplished, but I have no ideas. Currently, with such a small list, I just encourage users to try out all the options for themselves, since their own experiences are worth much more than someone else's statistics.

**Comment by allendema** [comment]
Didn't know that it is avaliable only over IPv6. 
As for the speed, yes it is a bit tricky.
Anyways, i appreciate your quick response.
