### ISSUE TITLE
Buttons to go through posts

### ISSUE THREAD

**Issue by Perflyst** [cloudrac3r/bibliogram#8]
On Instagram you can navigate through the posts with arrows which are on the left and right side of each post.
On Bibliogram you have to go back to the actual profile and click each post to view it

**Comment by cloudrac3r** [comment]
Where would the buttons be positioned on the page?

If the image page is loaded directly, and the user is not cached, how would I know which images come before or after in the timeline? I would have to load the entire timeline until I find the current image in order to see what comes before or after. This is gross.

Soon the post view will overlay on the user page, which means the browser can manage timeline sequencing on its own, but if JavaScript is disabled this overlay feature will not work, so I still need some server fallback to sequence the timeline.

I think I will just have to not display the arrows if the timeline is not cached on the server.

**Comment by Perflyst** [comment]
> Where would the buttons be positioned on the page?
Left and right side of the image, like on instagram.com?

If the posts will overlay the user page then it will be even better, I can wait for that feature of course

**Comment by cloudrac3r** [comment]
Now that we have post overlay, this should be possible.
