### ISSUE TITLE
Display that private accounts are private

### ISSUE THREAD

**Issue by Lomanic** [cloudrac3r/bibliogram#80]
Here is an example of a private account:

* https://bibliogram.art/u/mouloudachour
* https://www.instagram.com/mouloudachour

Currently it will show as if it doesn't have any posts (while it has some, only private), which is a bit confusing (one can think it's a bug in Bibliogram while it retrieves posts).

Is this info only displayed on a user page (no Graphql query available)?

**Comment by cloudrac3r** [comment]
I can't find a graphql to get whether the profile is private or not, but I do have another idea: if the profile has a post counter >0 and the get posts endpoint returns no posts then the profile must be private.

**Comment by guser-sudo** [comment]
And more importantly: that public accounts don't show up as private. It's really annoying to have to fish the post links from feeds (they are correct when available), other instances or instagram.

**Comment by cloudrac3r** [comment]
Public accounts should never be shown as private. Is there a specific profile that this happens on?

**Comment by cloudrac3r** [comment]
The original issue should be fixed in a8ca2330275861a0f5d9c90089d6b4292ae31260. https://bibliogram.art/u/mouloudachour is now marked as private.

**Comment by guser-sudo** [comment]
Thanks, my issue is fixed, too, for now.
However to verify this never happens again, one needs to wait for a user to switch from private to public. Only then bibliogram sometimes got stuck on private forever.

**Comment by cloudrac3r** [comment]
I have added logic to set the profile to be marked as public if its posts are available.

If this doesn't work for some reason, if posts are available then they will now override the private profile notice. Previously it was the other way around.

You shouldn't have problems with private profiles becoming public again.

In future, if you notice a problem that depends on account state like a profile being private, or a username change, please let me know as soon as possible and include the name of the profile so that I can use it to verify the problem and test a fix with. If you do not wish to post it on GitHub, you can [contact me some other way](https://cadence.moe/about/contact) and I will file an issue on your behalf.

**Comment by Lomanic** [comment]
Thanks for the quick fix @cloudrac3r.
