### ISSUE TITLE
Full Instagram Interactively

### ISSUE THREAD

**Issue by FireMasterK** [cloudrac3r/bibliogram#86]
Users would be able to log in with their own accounts in bibliogram.

Why this is beneficial:
- Users can view private accounts
- Users would not be tracked via device ID, etc
- This potentially solves #77 
- Bibliogram can use the Tor for logging into accounts, thus improving the user's privacy and preventing the Instagram from identifying bibliogram users from other users.
- Gives users a feed that is personalized for the user

Potential Challenges:
- Deciding which API to use: Mobile / Web
- Multiple accounts
- Integration with #47 (potentially saving encrypted sessions on a bibliogram server?)
- Support for the Security Checks (email, sms and 2fa authentication)

**Comment by cloudrac3r** [comment]
**The accounts would be instantly flagged and banned for suspicious activity.**

- Logging in from a server IP: Probably about to be used for automated likes/follows/spam.
- Hundreds of logins from the same IP: Definitely part of a large campaign to be used for automated likes/follows/spam.
- Liking or following anything or creating any posts: Definitely part of a large campaign which is currently actively liking/following/spamming, and needs to be dealt with before it can have a large impact.

Instagram has to deal with stuff like this every day. It would be foolish to think that they do not have sophisticated ways to detect campaigns.

> Bibliogram can use Tor for logging into accounts, thus improving the user's privacy and preventing the Instagram from identifying bibliogram users from other users.

See above, but replace "server IP" with "Tor exit node IP". Tor would likely be treated as _more_ suspicious, if anything. [It's incredibly easy to detect if incoming requests are from the public Tor network.](https://2019.www.torproject.org/docs/faq-abuse.html.en#Bans)

Solving #77 does sound attractive, but it would only work if Instagram doesn't Insta​*ban* (heh) the accounts.

Finally, I only have a limited time to develop Bibliogram, and prioritising features that only a selection of people will care about is not the best use of my time.

I think that someone who wants these features could either fork Bibliogram or create a similar project to add these features, since I'm not interested. I think it would be much more viable if it was an Android/iOS app, since you would likely not be on their radar since you'd have one account logged in from the same IP rather than hundreds.

I do appreciate the bullet points you wrote though.
