### ISSUE TITLE
"Timeline loading blocked" poor contrast on dark theme

### ISSUE THREAD

**Issue by ghost** [cloudrac3r/bibliogram#97]
Minor cosmetics: With dark themes black text might be shown on dark background, e.g. the "Timeline loading blocked" message. That's a little bit hard to read.

**Comment by cloudrac3r** [comment]
Do you have a screenshot?

**Comment by guser-sudo** [comment]
No, I didn't make a screenshot.
The theme was `PussTheCat.org dark v1`. And the "Timeline loading blocked" message appeared directly as the last row in the timeline where the "Next page"-button would be. It's _not_ a separate error page, they look fine.

**Comment by guser-sudo** [comment]
Funny effect: I just had the "Timeline loading blocked" message on your instance which is nicely readable because of the light background of the default theme. Then I switched to a dark theme. The profile is initially shown with the dark theme but as soon as I scroll down the timeline to see the error message the theme auto-switches back to the default light one.
Is this already a fix you applied or just another strange effect?

PS: The original issue was on the pussthecat instance with their default dark theme.

**Comment by cloudrac3r** [comment]
Oops, the entire page becomes light because I'm mistakenly importing the global default theme stylesheet when the message loads because the blocked notice is actually a full page, not a fragment. I'll have to make this better, and add visual tests for it.

**Comment by cloudrac3r** [comment]
Fixed in 5ef9af5f0855df4adf85504203cd2265f1104b7c. No tests for it.
